# Generated by Django 3.2.20 on 2023-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicoweb', '0003_auto_20230911_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='titlle_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='fara tag', max_length=30),
        ),
    ]
