# Generated by Django 3.2.20 on 2023-09-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicoweb', '0007_auto_20230926_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
