# Generated by Django 3.2.20 on 2023-11-02 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicoweb', '0009_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 12, 20, 32, 549651)),
        ),
    ]
